# faça um programa que leia algo no teclado e mostre os tipos primitivos dele

# t = input('digite algo: ')
# print('é um numero?: ', t.isnumeric())
# print('tem espaços?: ', t.isspace())
# print('e alfabetico?: ', t.isalpha())
# print('é alfanumerico?: ', t.isalnum())
# print('ta em maiusculo?: ', t.isupper())
# print('ta em minusculo?: ', t.islower())
# print('ele esta captalizado?: ', t.istitle())

#print('quer saber qual e o tipo primitivo ? ')
#tipo_primitivo = input('digite algo: ')
#n = tipo_primitivo.isnumeric()
#esp = tipo_primitivo.isspace()
#alf = tipo_primitivo.isalpha()
#aln = tipo_primitivo.isalnum()
#M = tipo_primitivo.isupper()
#m = tipo_primitivo.islower()
#cap = tipo_primitivo.istitle()
#print(' tem numero?: {}\n tem espaço?: {}\n é alfabetico?: {}\n é alfanumerico?: {}\n ta em maiusculo?: {}\n ta em minusculo?: {}\n ta captalizado?: {}'.format(n,esp,alf,aln,M,m,cap))